Sonnet V1.2.2
Sonnet-Discord/sonnet-py pull request #56
Opened 2021-04-07 12:39 UTC by ultrabear

PR for Sonnet V1.2.2

2021-04-07 17:30 UTC, ultrabear commented
# Changelog:
## Frontend:
- Add stricter input validation to set-antispam
- Add set-mutetime command
- unban and unmute now insert reasons and logs into database
- note infractions are like warns but dont log to infraction log or dm the user
- Infraction searching now supports negative indexing
- rr-purge added to remove all reactionroles from a message
- map now takes -e parameter for appending args to the end of every command
- Add absolute totals to % totals in statistics command
- Support floating point seconds in antispam time
## Under the Hood:
- Added return state to most commands, allows sonnetsh and map to stop execution after a failure
- Remove unneeded imports from all files, this is thanks to the new addition of pyflakes and pylint in the workflow
- GDPR now instancizes commands before running them
- General infraction processor is no longer garbage
  - now gaurantees a user object or failure
  - can specify to not add an infraction to logs but put it in the database
  - just look at it its so much cleaner
- muting a user now first clears them from the mute database and unmuting will also clear them from the database
- Ping function now uses timestamp generation template function
- Uptime printing now uses shared function, no longer prints as "days" when the count of days is 1
- Userupdate no longer checks for changed usernames as that event happens on on-user-update
- Update kernel to LeXdPyK 1.3.1
  - Updates to support discord.py 1.7 deprecations
  - error printing is now pretty
## Runtime Environment:
- Make re2 optional
- Make loading the C lib optional
- Add default lite config for running the bot without mariadb or re2
- Move requirements.txt to requirements.txt and requirements.extras.txt to allow for not installing re2 or mariadb
## Bugs:
- Fix jkb on a non user would print None
- Fix negative mute times that would proceed to not mute
- Infraction searching no longer goes to last page when 0 is passed into it

2021-04-08 17:11 UTC, Saragon4005 requested changes

2021-04-08 17:11 UTC, Saragon4005 commented on libs/lib_loaders.py
> +            ],
thanks yapf

2021-04-08 17:11 UTC, Saragon4005 commented on requirements.txt
> +discord.py >= 1.7
```suggestion
discord.py >= 1.7.1
```
patch has been added

2021-04-08 17:13 UTC, ultrabear commented on cmds/cmd_moderation.py
> +        member, user, reason, _, dm_sent = await process_infraction(message, args, client, "ban")
ah yes and throw away the feature of banning someone not in the guild? nah

2021-04-08 17:13 UTC, ultrabear commented on cmds/cmd_moderation.py
> +        return (None, None)
yeah

2021-04-08 17:23 UTC, ultrabear commented on cmds/cmd_automod.py
> +            'description': 'Set how long a person should be muted for with antispam automute',
fixed in 91d79f1b1355d06b7aa807d84f016e7685046311

2021-04-08 17:23 UTC, ultrabear commented on cmds/cmd_automod.py
> +    if kwargs["verbose"]: await message.channel.send(f"Updated antispam timings to M:{int(messages)},S:{seconds}")
fixed in 91d79f1b1355d06b7aa807d84f016e7685046311

2021-04-08 17:24 UTC, Saragon4005 approved these changes

2021-04-08 17:29 UTC, merged