Sonnet V1.2.7
Sonnet-Discord/sonnet-py pull request #76
Opened 2021-08-24 20:23 UTC by ultrabear

Bruh I didn't think dpy2.0 would take this long to come out

2021-08-28 21:26 UTC, ultrabear commented
# Changelog
## Frontend:
- Add(starboard-forceboard): allows forcing a message to be starboarded
- Change(mute): under gotools parser, 5m2s type parsing is allowed now
## Under the Hood:
- Change(search-infractons): Improve infraction renderer to show most amount of chars possible
- Add: gotools library to handle time parsing
- Add: gotools GenerateCacheFile (10x as fast as python variant)
- Change: move alot of code to use io.StringIO
- Add: dpy-stubs typing to codebase
- Change: remove --implicit-reexport mypy flag as its no longer needed
- LeXdPyK 1.4: support for dpy typing, faster ramfs multi dir lookups
- Add(lib_sonnetconfig): Support for dynamic config loading
- Change: reformat wordlist to be alphabetic, add new words
- Change(parsedate): parsedate functions now take optional datetime to conform to dpy typing
- Add: Starting stubs for a new database version, this is not finalized
## Runtime Environment:
- Add: new configs without breaking old config files: `GOLIB_LOAD` and `GOLIB_VERSION`
## Bugs:
- Patch: Remove alot of race conditions and channel type errors by adding dpy typing
- Patch(help): Help command total commands count was not correct
- Patch(cloader): Make cloader differentiate between processing error and FileNotFound
- Patch(update_log_channel): now checks for type of channel, must be TextChannel

2021-08-30 17:10 UTC, Saragon4005 requested changes

2021-08-30 17:10 UTC, Saragon4005 commented on libs/lib_loaders.py
> +                num_words = ((words.seek(0, io.SEEK_END) or 0) - 1) // chunksize
what does this do and why?

2021-08-30 17:10 UTC, Saragon4005 commented on dlibs/dlib_userupdate.py
> +    if abs(datetime_now().timestamp() - member.created_at.timestamp()) < int(notifier_cache["notifier-log-timestamp"]):
```suggestion
    if abs(datetime.utcnow().timestamp() - member.created_at.timestamp()) < int(notifier_cache["notifier-log-timestamp"]):
```

2021-08-30 17:12 UTC, Saragon4005 approved these changes

2021-08-30 19:54 UTC, ultrabear commented
Note: there are very few features added this version, because sonnet core is now a stable base, see sonnet-modules for new ideas and tools.

2021-08-30 20:02 UTC, ultrabear commented
This PR took so long to approve that discord.py discord.died :sob:

2021-08-30 22:36 UTC, merged